tushare:
  token: "{TUSHARE_Token}"

paths:
  raw_root: "./data/raw"
  factor_root: "./data/factor"
  meta_db: "./data/meta/datahub.db"

update:
  start_date: "20180101"
  exchange: "SSE"
  sleep_seconds: 0.2
